// This file is auto-generated by download_coins.py
export const coins = [
  { name: 'Bitcoin', ticker: 'BTC', image: '/coins/btc.png' },
  { name: 'Ethereum', ticker: 'ETH', image: '/coins/eth.png' },
  { name: 'Tether', ticker: 'USDT', image: '/coins/usdt.png' },
  { name: 'XRP', ticker: 'XRP', image: '/coins/xrp.png' },
  { name: 'BNB', ticker: 'BNB', image: '/coins/bnb.png' },
  { name: 'Solana', ticker: 'SOL', image: '/coins/sol.png' },
  { name: 'Dogecoin', ticker: 'DOGE', image: '/coins/doge.png' },
  { name: 'USDC', ticker: 'USDC', image: '/coins/usdc.png' },
  { name: 'Lido Staked Ether', ticker: 'STETH', image: '/coins/steth.png' },
  { name: 'Cardano', ticker: 'ADA', image: '/coins/ada.png' },
];
